users=[{"id":1,"name":"Lia","gender":"Female","location":"Butel"},
{"id":2,"name":"Larine","gender":"Female","location":"Dolod"},
{"id":3,"name":"Hasty","gender":"Male","location":"Chowṉêy"},
{"id":4,"name":"Cherri","gender":"Female","location":"Pedroso"},
{"id":5,"name":"Viole","gender":"Female","location":"Buje"},
{"id":6,"name":"Susana","gender":"Female","location":"Yuyue"},
{"id":7,"name":"Hannis","gender":"Genderqueer","location":"Thepharak"},
{"id":8,"name":"Christi","gender":"Female","location":"Manukau City"},
{"id":9,"name":"Marie-jeanne","gender":"Female","location":"Muang Sing"},
{"id":10,"name":"Dilly","gender":"Male","location":"Padina"},
{"id":11,"name":"Lavinia","gender":"Female","location":"Acopiara"},
{"id":12,"name":"Viki","gender":"Female","location":"Bentar"},
{"id":13,"name":"Wayne","gender":"Male","location":"Wucun"},
{"id":14,"name":"Tymothy","gender":"Male","location":"Staraya Kulatka"},
{"id":15,"name":"Jolene","gender":"Female","location":"Profítis Ilías"},
{"id":16,"name":"Marie","gender":"Female","location":"Turbaco"},
{"id":17,"name":"Damiano","gender":"Male","location":"Wanli"},
{"id":18,"name":"Stefa","gender":"Female","location":"Hroznětín"},
{"id":19,"name":"Dianemarie","gender":"Female","location":"Warri"},
{"id":20,"name":"Levy","gender":"Male","location":"Cát Bà"},
{"id":21,"name":"Sella","gender":"Female","location":"Mafraq"},
{"id":22,"name":"Gaelan","gender":"Male","location":"Kovrov"},
{"id":23,"name":"Hewitt","gender":"Male","location":"Sangat"},
{"id":24,"name":"Staford","gender":"Male","location":"Yuci"},
{"id":25,"name":"Hansiain","gender":"Male","location":"Cibodas"},
{"id":26,"name":"Mina","gender":"Bigender","location":"Prapen"},
{"id":27,"name":"Freida","gender":"Female","location":"Ma’ao"},
{"id":28,"name":"Coop","gender":"Male","location":"Sedlice"},
{"id":29,"name":"Candi","gender":"Genderqueer","location":"Kołaczyce"},
{"id":30,"name":"Nancy","gender":"Female","location":"Miastków Kościelny"},
{"id":31,"name":"Reinaldos","gender":"Polygender","location":"Venda Nova"},
{"id":32,"name":"Addie","gender":"Female","location":"Youssoufia"},
{"id":33,"name":"Doloritas","gender":"Female","location":"Na Muen"},
{"id":34,"name":"Klaus","gender":"Male","location":"Zapod"},
{"id":35,"name":"Coop","gender":"Polygender","location":"Bīrganj"},
{"id":36,"name":"Carolina","gender":"Female","location":"Mungkin"},
{"id":37,"name":"Abigale","gender":"Female","location":"Marcq-en-Barœul"},
{"id":38,"name":"Hermina","gender":"Non-binary","location":"Jeblog Satu"},
{"id":39,"name":"Chrysler","gender":"Female","location":"Kufayrit"},
{"id":40,"name":"Robinia","gender":"Bigender","location":"Kertosari"},
{"id":41,"name":"Lorena","gender":"Female","location":"Newala Kisimani"},
{"id":42,"name":"Jareb","gender":"Male","location":"Sipirok"},
{"id":43,"name":"Merl","gender":"Female","location":"Seroa"},
{"id":44,"name":"Miran","gender":"Female","location":"Garland"},
{"id":45,"name":"Berne","gender":"Male","location":"Mulatupo"},
{"id":46,"name":"Graeme","gender":"Male","location":"Ifanadiana"},
{"id":47,"name":"Evania","gender":"Polygender","location":"Oleiros"},
{"id":48,"name":"Roxanna","gender":"Female","location":"Gore"},
{"id":49,"name":"Brett","gender":"Male","location":"Puunage"},
{"id":50,"name":"Hildagarde","gender":"Female","location":"Huangcun"},
{"id":51,"name":"Federico","gender":"Male","location":"Otorohanga"},
{"id":52,"name":"Gothart","gender":"Male","location":"Xiaochengzi"},
{"id":53,"name":"Franzen","gender":"Male","location":"Ḩājjīābād"},
{"id":54,"name":"Elfreda","gender":"Female","location":"Villa Bisonó"},
{"id":55,"name":"Meade","gender":"Female","location":"Libon"},
{"id":56,"name":"Garrard","gender":"Male","location":"Artemivs’k"},
{"id":57,"name":"Delmor","gender":"Male","location":"Avignon"},
{"id":58,"name":"Tiebout","gender":"Male","location":"San José"},
{"id":59,"name":"Napoleon","gender":"Male","location":"Bangassou"},
{"id":60,"name":"Lita","gender":"Female","location":"Yanggu’ao"},
{"id":61,"name":"Bellanca","gender":"Female","location":"Chlumčany"},
{"id":62,"name":"Tracee","gender":"Female","location":"Gununggoong"},
{"id":63,"name":"Liana","gender":"Female","location":"Paleran"},
{"id":64,"name":"Larina","gender":"Female","location":"Shizong"},
{"id":65,"name":"Midge","gender":"Female","location":"Yangdu"},
{"id":66,"name":"Burton","gender":"Male","location":"Béziers"},
{"id":67,"name":"Glenden","gender":"Male","location":"Páchni"},
{"id":68,"name":"Avram","gender":"Male","location":"Mikulčice"},
{"id":69,"name":"Anabal","gender":"Genderfluid","location":"Tianhekou"},
{"id":70,"name":"Paquito","gender":"Male","location":"Mentougou"},
{"id":71,"name":"Lissa","gender":"Female","location":"Velikooktyabr’skiy"},
{"id":72,"name":"Adorne","gender":"Bigender","location":"Kedungsinggil"},
{"id":73,"name":"Ursola","gender":"Female","location":"Zvenyhorodka"},
{"id":74,"name":"Fletch","gender":"Non-binary","location":"Saint Louis"},
{"id":75,"name":"Lauren","gender":"Male","location":"Lebak"},
{"id":76,"name":"Maxwell","gender":"Male","location":"Inđija"},
{"id":77,"name":"Diarmid","gender":"Male","location":"Teruel"},
{"id":78,"name":"Mandel","gender":"Male","location":"Suibara"},
{"id":79,"name":"Hamish","gender":"Bigender","location":"Kuala Lumpur"},
{"id":80,"name":"Papagena","gender":"Female","location":"Millet"},
{"id":81,"name":"Nancy","gender":"Female","location":"Jinqu"},
{"id":82,"name":"Chandal","gender":"Female","location":"Concordia"},
{"id":83,"name":"Carolann","gender":"Female","location":"Sarnaki"},
{"id":84,"name":"Clair","gender":"Male","location":"Murom"},
{"id":85,"name":"Camel","gender":"Female","location":"Rennes"},
{"id":86,"name":"Eddy","gender":"Male","location":"Berbérati"},
{"id":87,"name":"Rupert","gender":"Male","location":"Belén de los Andaquíes"},
{"id":88,"name":"Krystle","gender":"Female","location":"Le Cannet"},
{"id":89,"name":"Templeton","gender":"Male","location":"Pilar"},
{"id":90,"name":"Meredith","gender":"Agender","location":"Jacarezinho"},
{"id":91,"name":"Gaston","gender":"Male","location":"Al Jubayhah"},
{"id":92,"name":"Elsi","gender":"Genderqueer","location":"Zherdevka"},
{"id":93,"name":"Gerrard","gender":"Male","location":"Bécancour"},
{"id":94,"name":"Saunders","gender":"Non-binary","location":"Yangjiaping"},
{"id":95,"name":"Julius","gender":"Male","location":"Sukamulya"},
{"id":96,"name":"Millisent","gender":"Female","location":"Gorki Vtoryye"},
{"id":97,"name":"Anallise","gender":"Female","location":"Calçada"},
{"id":98,"name":"Maryellen","gender":"Female","location":"Ipuh"},
{"id":99,"name":"Gabbey","gender":"Female","location":"Anling"},
{"id":100,"name":"Gweneth","gender":"Female","location":"Minnedosa"}]
 #print no of male users from the given list
male_user_count=0
female_user_count=0
for user in users:
    if user["gender"]=="Male":
        male_user_count=male_user_count+1

    elif user["gender"]=="Female":
        female_user_count=female_user_count+1


print("No of Male User: ", male_user_count)
print("No of Female User: ", female_user_count)

